### ISSUE TITLE
Some questions about your code

### ISSUE THREAD

**Issue by qdd1234** [chenbinghui1/DSL#3]
Hi, thanks for your wonderful work! Where can I find the code about Adaptive Filtering Strategy? Thanks!

**Comment by chenbinghui1** [comment]
The implementation of AF is composed of several parts:
(1) ignore-label assignment:
https://github.com/chenbinghui1/DSL/blob/72338c3a713b057cd8388f4ee10b5a1160f4dee7/mmdet/datasets/semicoco.py#L232
Because the DSL-style data annotation file contains bboxes, tags, scores information, when we load the annos we can assign each instance into FG, Ignorable Region or BG according to the scores and  thresholds. Scores and thresholds \tao_{2} will be updated by mmdet/runner/hooks/unlabel_pred_hook.py.

(2) loss computation:
https://github.com/chenbinghui1/DSL/blob/72338c3a713b057cd8388f4ee10b5a1160f4dee7/mmdet/models/dense_heads/fcos_head.py#L209
Ignored region will ge weighted by 0 when computing losses.

(3) Adaptive \tao_{2} update:
https://github.com/chenbinghui1/DSL/blob/72338c3a713b057cd8388f4ee10b5a1160f4dee7/mmdet/runner/hooks/unlabel_pred_hook.py#L295

After each epoch, we will update \tao_{2} for each class, and the thresholds for each classes will be saved in json file "adathres.json" which is defined in config_file(https://github.com/chenbinghui1/DSL/blob/72338c3a713b057cd8388f4ee10b5a1160f4dee7/configs/fcos_semi/RLA_r50_caffe_mslonger_tricks_0.Xdata_unlabel_dynamic_lw_nofuse_iterlabel_si-soft_singlestage.py#L141)

(4) Instance score update:
https://github.com/chenbinghui1/DSL/blob/72338c3a713b057cd8388f4ee10b5a1160f4dee7/mmdet/runner/hooks/unlabel_pred_hook.py#L455-L469

Here, we will update the annotation file of each image in iter-manner(or epoch-manner, you can try by yourself, we also provide other kinds of update, e.g. fuse with pseudo-labels in history like in ISMT. )
